### ISSUE TITLE
MySql ORM issues with 'long' as ormtype

### ISSUE THREAD

**Issue by DrewNathanson** [GregoryAlexander77/Galaxie-Blog#42]
It would appear that the ormtype='long' in the comment.cfc, Commenter.cfc, Post.cfc, PodContainer.cfc and Users.cfc will cause an error in using MySql database. If you change this to ormtype="string", this resolves the error however further testing needs to be done to ensure the length is correct.

**Comment by GregoryAlexander77** [comment]
Thank-you Drew! I will test this and fix it soon!

**Comment by GregoryAlexander77** [comment]
I changed the definition of the columns that used to be ormtype="long" to ormtype="text" sqltype="longtext". I will upload the new files once I am done testing. Thanks for the input Drew!

**Comment by GregoryAlexander77** [comment]
The prior settings worked with MariaDb, but failed with MySql. Changed ormtype to string and sqltype to longtext.
